name: Apptainer Build

on:
  workflow_dispatch

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build Apptainer image
    permissions:
        contents: read
        packages: write
    steps:
      - name: Install Apptainer
        uses: uw-psych/apptainer-actions/setup
      - name: Check out code for the container build
        uses: actions/checkout@v4
      - name: Build Container
        uses: uw-psych/apptainer-actions/build-and-push
        with:
          deffile: 'Singularity'
          apptainer-tmpdir: ${{ github.workspace }}/apptainer-tmp
          image-dir: ${{ github.workspace }}
          image-version: ${{ github.ref_name }}

